import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SmoothScroll from "@/components/smooth-scroll";
import ScrollLogger from "@/components/scrollLogger";
import AOSInit from "@/components/AOS";
import "aos/dist/aos.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${inter.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <AOSInit/>
        <div className="side_gap">
          <Navbar />
          <SmoothScroll>
            <ScrollLogger />
            <main className="min-h-screen">
              {children}
            </main>
          </SmoothScroll>
        </div>
      </body>
    </html>
  );
}
