import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SmoothScroll from "@/components/smooth-scroll";
import ScrollLogger from "@/components/scrollLogger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="side_gap">
          <Navbar />
          <SmoothScroll>
            <ScrollLogger />
            <main className="min-h-screen">
              {children}
            </main>
          </SmoothScroll>
        </div>
      </body>
    </html>
  );
}
